version: '3.3'
services:
  r99-pg:
    image: postgres
    # expose:
    #   - "5432"
    # ports:
    #   - "5432:5432"
    volumes:
      - r99-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"

  r99-app:
    image: hkim/roswell
    ports:
      - "4005:4005"
      - "3030:3030"
    volumes:
      - ~/common-lisp/r99:/home/ubuntu/common-lisp/r99
    working_dir: /home/ubuntu/common-lisp/r99/src
    links:
      - r99-pg
    env_file: .env

volumes:
  r99-data:
    driver: local
